export const optionsType = [
  { label: "All", value: null },
  { label: "Word", value: 1 },
  { label: "Phrase", value: 2 },
  { label: "Question", value: 3 },
];

export const optionsTopic = [
  { label: "UNIT 1: GENERAL GREETING FOR FRIENDS", value: 1 },
  { label: "UNIT 2: AT A RESTAURANT", value: 2 },
  { label: "UNIT 3: AT THE PHARMACY - AT THE HOSPITAL", value: 3 },
  {
    label: "UNIT 4: AT THE BANK - AT THE TRAIN STATION - AT THE CINEMA",
    value: 4,
  },
  { label: "UNIT 5: HOBBY (GOING SHOPPING & TRAVELLING)", value: 5 },
  { label: "UNIT 6: SPOKEN ENGLISH FOR OFFICE STAFF", value: 6 },
  { label: "UNIT 7: CITY AND COUNTRYSIDE", value: 7 },
  { label: "UNIT 8: INTERNET", value: 8 },
  { label: "UNIT 9: FASHION", value: 9 },
  { label: "UNIT 10: SPORTS", value: 10 },
  { label: "UNIT 11: HEALTH", value: 11 },
];

export const globalData = [
  // Unit 1
  {
    type: 1,
    unit: 1,
    data: [
      "fine",
      "great",
      "well",
      "bad",
      "in a hurry",
      "take care",
      "complain",
      "better",
      "available",
      "confirm",
      "department",
      "experience",
      "competent",
      "information",
      "appreciation",
      "schedule",
      "influence",
      "experience",
    ],
  },
  {
    type: 2,
    unit: 1,
    data: [
      "Hello, may I speak to...",
      "I’m afraid, he is not available now",
      "He is on another line",
      "I’m in a hurry now",
      "I will leave a message",
      "Shall we make it 2 o'clock?",
      "Is there any possibility we can move the meeting to Monday?",
      "So, to confirm, you are Ms. Ngoc Lan of SunUni Company, correct?",
      "I'll pass along the message to Mr. Smith",
      "I can’t complain too much.",
    ],
  },
  {
    type: 3,
    unit: 1,
    data: [
      "Where are you going?",
      "Would you like to schedule an appointment?",
      "How are you today?",
      "Would you mind holding?",
      "How’s your life?",
      "What are you doing these days?",
      "What are you doing these days?",
    ],
  },
  // Unit 2
  {
    type: 1,
    unit: 2,
    data: [
      "Szechuan Dumplings - Sủi cảo Tứ Xuyên",
      "Fresh Shrimp Dumplings - Há cảo tôm tươi",
      "Char Siu Bao - Bánh bao xá xíu",
      "Rice with Beef Sauce",
      "Szechuan Tofu - Đậu hủ Tứ Xuyên",
      "Hong Kong Wontons - Hoành thánh Hongkong",
      "Peking Roast Duck - Vịt quay Bắc Kinh",
      "Rice with Seafood Sauce",
      "Steamed Egg Custard Buns - Bánh bao trứng sữa",
      "reservation",
      "drink",
      "eat",
      "waiter",
      "waitress",
      "juice",
      "order",
      "comfortable",
      "Appetizer",
      "Starter",
      "Entrée",
      "Main course",
      "Dessert",
      "Roasted food",
      "Grilled food",
      "Saute food",
      "Steam food",
      "Alcohol",
      "Good evening",
    ],
  },
  {
    type: 2,
    unit: 2,
    data: [
      "I have a reservation...",
      "I refer...",
      "I think I'll have ... to begin with",
      "I'll order...",
      "Bring me...",
      "Give me the bill, please",
      "It's my treat this time. I'll pay",
      "Everything's great, thank you.",
      "Here you go. Just let me know when you're ready to pay",
      "That was a fantastic meal. Thank you",
      "I'm glad you enjoyed it. Have a great evening!",
      "I'd like to make a reservation",
      "right this way",
      "follow me",
      "it's under the name Ngoc Lan",
      "Here are your menus",
      "I'd like some coffee",
      "I don't have any coffee",
      "I'll have a glass of water",
      "A small glass, or big one?",
      "Small, please",
      "I'm hungry. I'd like to eat something",
      "I'd like to go to a Chinese restaurant",
      "at 11 PM",
      "Sorry, that's too late, I usually go to bed around 10 PM",
      "No, that's too early, I'll still be at work then",
      "That's fine",
      "Ok, see you then",
      "Hey waiter, I want to pay",
      "I wanna sit next to the window, so I can see the street",
      "I want coca",
    ],
  },
  {
    type: 3,
    unit: 2,
    data: [
      "May I have your name, please?",
      "welcome to [Restaurant Name]. Do you have a reservation for tonight?",
      "Can I get you anything else?",
      "Here you go. Just let me know when you're ready to...",
      "Would you like something to eat?",
      "Do you want something to drink?",
      "What do you want to do?",
      "Where do you want to go?",
      "Would you like to get something to eat with me?",
      "How about 3 PM?",
      "How about 7 PM?",
      "Do you want to go out to dinner with me?",
      "what would you like to eat now?",
      "Can I have the menu, please?",
      "What would you like to drink, little girl?",
    ],
  },
  // Unit 3
  {
    type: 1,
    unit: 3,
    data: [
      "sore throat",
      "cold",
      "flu",
      "fever",
      "runny nose",
      "dizzy",
      "diarrhoea",
      "indigestion",
      "burn",
      "food poisoning",
      "toothache",
      "backache",
      "stomachache",
      "symptom",
    ],
  },
  {
    type: 2,
    unit: 3,
    data: [
      "Take this medicine to relieve your pain",
      "Drink warm lemon with honey to ease your pain",
      "Drink plenty of fluids and take a rest",
      "Rinse your mouth with warm salt water to help ease your pain",
      "Avoid spicy or greasy foods",
      "Apply a heating pad or ice pack to the affected area",
      "Apply burn ointment to the affected area",
      "I need some burn ointment",
      "You need...",
      "You should...",
      "I’ve got a...",
      "I have a...",
      "My symptoms include...",
      "wash your hands with cold water",
      "seek medical attention",
    ],
  },
  {
    type: 3,
    unit: 3,
    data: [
      "What are they suffering from?",
      "Can I help you?",
      "How long have you had it?",
      "Do you have the prescription with you?",
      "Do you need anything else?",
      "What are your symptoms?",
    ],
  },
  // Unit 4
  {
    type: 1,
    unit: 4,
    data: [
      "open an account",
      "make a deposit",
      "make a withdrawal",
      "close out my account",
      "identification",
      "fill out - filling out",
      "cash",
      "passbook",
      "account number",
      "ID card",
      "account balance",
      "interest rate",
      "savings account",
    ],
  },
  {
    type: 2,
    unit: 4,
    data: [
      "I'd like to open an account",
      "I need to make a...",
      "fill out this withdrawal form",
      "I'd like to...",
      "Once you finish filling out this form, your account will be set up!",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
  {
    type: 3,
    unit: 4,
    data: [
      "Do you have any identification with you?",
      "How much would you like to deposit today?",
      "What is the annual interest rate for savings accounts?",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
];
