export const optionsType = [
  { label: "All", value: null },
  { label: "Word", value: 1 },
  { label: "Phrase", value: 2 },
  { label: "Question", value: 3 },
];

export const optionsTopic = [
  { label: "UNIT 1: GENERAL GREETING FOR FRIENDS", value: 1 },
  { label: "UNIT 2: AT A RESTAURANT", value: 2 },
  { label: "UNIT 3: AT THE PHARMACY - AT THE HOSPITAL", value: 3 },
  {
    label: "UNIT 4: AT THE BANK - AT THE TRAIN STATION - AT THE CINEMA",
    value: 4,
  },
  { label: "UNIT 5: HOBBY (GOING SHOPPING & TRAVELLING)", value: 5 },
  { label: "UNIT 6: SPOKEN ENGLISH FOR OFFICE STAFF", value: 6 },
  { label: "UNIT 7: CITY AND COUNTRYSIDE", value: 7 },
  { label: "UNIT 8: INTERNET", value: 8 },
  { label: "UNIT 9: FASHION", value: 9 },
  { label: "UNIT 10: SPORTS", value: 10 },
  { label: "UNIT 11: HEALTH", value: 11 },
  { label: "UNIT 12: QUESTIONS", value: 12 },
];

export const globalData = [
  // Unit 1
  {
    type: 1,
    unit: 1,
    data: [
      "fine",
      "great",
      "well",
      "bad",
      "in a hurry",
      "take care",
      "complain",
      "better",
      "available",
      "confirm",
      "department",
      "experience",
      "competent",
      "information",
      "appreciation",
      "schedule",
      "influence",
      "experience",
    ],
  },
  {
    type: 2,
    unit: 1,
    data: [
      "Hello, may I speak to...",
      "I’m afraid, he is not available now",
      "He is on another line",
      "I’m in a hurry now",
      "I will leave a message",
      "Shall we make it 2 o'clock?",
      "Is there any possibility we can move the meeting to Monday?",
      "So, to confirm, you are Ms. Ngoc Lan of SunUni Company, correct?",
      "I'll pass along the message to Mr. Smith",
      "I can’t complain too much.",
    ],
  },
  {
    type: 3,
    unit: 1,
    data: [
      "Where are you going?",
      "Would you like to schedule an appointment?",
      "How are you today?",
      "Would you mind holding?",
      "How’s your life?",
      "What are you doing these days?",
      "What are you doing these days?",
    ],
  },
  // Unit 2
  {
    type: 1,
    unit: 2,
    data: [
      "Szechuan Dumplings - Sủi cảo Tứ Xuyên",
      "Fresh Shrimp Dumplings - Há cảo tôm tươi",
      "Char Siu Bao - Bánh bao xá xíu",
      "Rice with Beef Sauce",
      "Szechuan Tofu - Đậu hủ Tứ Xuyên",
      "Hong Kong Wontons - Hoành thánh Hongkong",
      "Peking Roast Duck - Vịt quay Bắc Kinh",
      "Rice with Seafood Sauce",
      "Steamed Egg Custard Buns - Bánh bao trứng sữa",
      "reservation",
      "drink",
      "eat",
      "waiter",
      "waitress",
      "juice",
      "order",
      "comfortable",
      "Appetizer",
      "Starter",
      "Entrée",
      "Main course",
      "Dessert",
      "Roasted food",
      "Grilled food",
      "Saute food",
      "Steam food",
      "Alcohol",
      "Good evening",
    ],
  },
  {
    type: 2,
    unit: 2,
    data: [
      "I have a reservation...",
      "I refer...",
      "I think I'll have ... to begin with",
      "I'll order...",
      "Bring me...",
      "Give me the bill, please",
      "It's my treat this time. I'll pay",
      "Everything's great, thank you.",
      "Here you go. Just let me know when you're ready to pay",
      "That was a fantastic meal. Thank you",
      "I'm glad you enjoyed it. Have a great evening!",
      "I'd like to make a reservation",
      "right this way",
      "follow me",
      "it's under the name Ngoc Lan",
      "Here are your menus",
      "I'd like some coffee",
      "I don't have any coffee",
      "I'll have a glass of water",
      "A small glass, or big one?",
      "Small, please",
      "I'm hungry. I'd like to eat something",
      "I'd like to go to a Chinese restaurant",
      "at 11 PM",
      "Sorry, that's too late, I usually go to bed around 10 PM",
      "No, that's too early, I'll still be at work then",
      "That's fine",
      "Ok, see you then",
      "Hey waiter, I want to pay",
      "I wanna sit next to the window, so I can see the street",
      "I want coca",
    ],
  },
  {
    type: 3,
    unit: 2,
    data: [
      "May I have your name, please?",
      "welcome to [Restaurant Name]. Do you have a reservation for tonight?",
      "Can I get you anything else?",
      "Here you go. Just let me know when you're ready to...",
      "Would you like something to eat?",
      "Do you want something to drink?",
      "What do you want to do?",
      "Where do you want to go?",
      "Would you like to get something to eat with me?",
      "How about 3 PM?",
      "How about 7 PM?",
      "Do you want to go out to dinner with me?",
      "what would you like to eat now?",
      "Can I have the menu, please?",
      "What would you like to drink, little girl?",
    ],
  },
  // Unit 3
  {
    type: 1,
    unit: 3,
    data: [
      "sore throat",
      "cold",
      "flu",
      "fever",
      "runny nose",
      "dizzy",
      "diarrhoea",
      "indigestion",
      "burn",
      "food poisoning",
      "toothache",
      "backache",
      "stomachache",
      "symptom",
    ],
  },
  {
    type: 2,
    unit: 3,
    data: [
      "Take this medicine to relieve your pain",
      "Drink warm lemon with honey to ease your pain",
      "Drink plenty of fluids and take a rest",
      "Rinse your mouth with warm salt water to help ease your pain",
      "Avoid spicy or greasy foods",
      "Apply a heating pad or ice pack to the affected area",
      "Apply burn ointment to the affected area",
      "I need some burn ointment",
      "You need...",
      "You should...",
      "I’ve got a...",
      "I have a...",
      "My symptoms include...",
      "wash your hands with cold water",
      "seek medical attention",
    ],
  },
  {
    type: 3,
    unit: 3,
    data: [
      "What are they suffering from?",
      "Can I help you?",
      "How long have you had it?",
      "Do you have the prescription with you?",
      "Do you need anything else?",
      "What are your symptoms?",
    ],
  },
  // Unit 4
  {
    type: 1,
    unit: 4,
    data: [
      "open an account",
      "make a deposit",
      "make a withdrawal",
      "close out my account",
      "identification",
      "fill out - filling out",
      "cash",
      "passbook",
      "account number",
      "ID card",
      "account balance",
      "interest rate",
      "savings account",
      "reserve a seat",
      "a window seat",
      "first-class seat",
      "second-class seat",
      "a one-way",
      "round-trip",
    ],
  },
  {
    type: 2,
    unit: 4,
    data: [
      "I'd like to open an account",
      "I need to make a...",
      "fill out this withdrawal form",
      "I'd like to...",
      "Once you finish filling out this form, your account will be set up!",
      "I'm happy to help you with that",
      "I'd like to reserve a seat on the 9:00 train, if possible.",
      "Window seat would be perfect",
      "Would you like a return ticket?",
      "We can try reserving online",
      "Looks like there aren't any tickets left in the front rows",
      "I don't like being near the screen anyway.",
      "Let’s sit at the back",
    ],
  },
  {
    type: 3,
    unit: 4,
    data: [
      "Do you have any identification with you?",
      "How much would you like to deposit today?",
      "What is the annual interest rate for savings accounts?",
      "How much is a ticket to Sapa?",
      "Do you prefer a first-class or second-class seat?",
      "Would you like a window seat?",
      "Is it a one-way or return ticket?",
      "How much would that be in total?",
      "Would you like to go to a movie tonight?",
      "Where can I buy tickets?",
    ],
  },
  // Unit 5
  {
    type: 1,
    unit: 5,
    data: [
      "hobby",
      "coding",
      "hitting the gym",
      "hanging out with my friends",
      "listening to music",
      "traveling",
      "improve my skills",
      "keep fit",
      "stay healthy",
      "relieves stress",
      "work and study burdens",
      "at a clothing store",
      "the blue one",
      "pair of shoes",
      "at a shoe store",
    ],
  },
  {
    type: 2,
    unit: 5,
    data: [
      "My hobbies are...",
      "I'm interested in...",
      "I'd like coding and hitting the gym",
      "I'm into...",
      "Hanging out with my friends gives me funny moments.",
      "Listening to music helps me relax from work and study burdens",
      "Traveling gives me exciting experiences",
      "I usually wear a medium",
      " I'm looking for...",
      "I prefer...",
      "we have some new arrivals in those colors",
      "The fitting/changing rooms are right over there.",
      "Yes, I would. How much is it?",
      "Thank you for your purchase! Here’s your receipt. Have a great day!",
      "I wear a size 42.",
      "Let me show you some options",
      "They both look good",
      "It looks good on me/you",
    ],
  },
  {
    type: 3,
    unit: 5,
    data: [
      "What’s your hobby?",
      "What are you interested in?",
      "What do you like to do?",
      "What are you into?",
      "How long have you hit the gym?",
      "How long have you coded?",
      "Why did you decide to learn coding?",
      "Why do you enjoy hitting the gym?",
      "Why do you enjoy listening to music?",
      "Why do you enjoy traveling?",
      "Why do you enjoy hanging out with your friends?",
      "Excuse me, can you help me find a shirt in my size?",
      "What size are you looking for?",
      "These look nice. Can I try them on? / it on?",
      "Would you like to purchase it?",
      "Would you like to pay with cash or credit card?",
      "What size do you need?",
    ],
  },
  // Unit 6
  {
    type: 1,
    unit: 6,
    data: [
      "our new team member",
      "Nice to meet you all",
      "report",
      "appointment",
      "calendar",
      "apologize",
      "permission",
      "position",
      "reason",
    ],
  },
  {
    type: 2,
    unit: 6,
    data: [
      "I’d like to introduce our new team member",
      "I’m really excited to be here.",
      "Welcome to the team",
      "We're glad to have you with us",
      "If you have any questions or need any help, feel free to ask.",
      "I appreciate it.",
      "I just arrived a little while ago.",
      "Let’s get you settled at your desk",
      "I’ll show you where you’ll be working and help you get started.",
      "I’m looking forward to getting started",
      "I’ll show you to your desk and introduce you to a few more colleagues along the way.",
    ],
  },
  {
    type: 3,
    unit: 6,
    data: [
      "Have you had a chance to look around the office yet?",
      "Kim, could you help Nam get set up?",
      "Could you repeat the telephone number, please?",
      "When will he be back?",
      "Could you please sign this report?",
      "Have you finished the report yet?",
      "Did you contact Mr. Taylor yesterday?",
      "Would you mind signing this report?",
    ],
  },
  // Unit 7
  {
    type: 1,
    unit: 7,
    data: [
      "city",
      "countryside",
      "rural areas",
      "air quality",
      "job opportunities",
      "pace of life",
      "poorer air quality",
      "lead to",
      "cause",
      "due to",
      "traffic",
      "industry",
      "vehicle",
      "factory",
      "cleaner",
      "healthier",
      "breathe",
      "agriculture",
      "local businesses,",
      "fast",
      "vibrant",
      "slower",
      "lifestyle",
      "career growth",
    ],
  },
  {
    type: 2,
    unit: 7,
    data: [
      "Cities often have poorer air quality",
      "leading to potential health issues",
      "The air is cleaner and healthier to breathe.",
      "Cities offer a wide range of job opportunities in various industries",
      "more chances for career growth",
      "The countryside has fewer job options",
      "The pace of life in the countryside is slower",
      "It can reduce stress and lead to a more relaxed lifestyle.",
    ],
  },
  {
    type: 3,
    unit: 7,
    data: [
      "What do you think about Air quality in the city?",
      "What do you think about Air quality in the countryside?",
      "What do you think about Job Opportunities in the city?",
      "What do you think about Job Opportunities the countryside?",
      "What do you think about Pace of Life in the city?",
      "What do you think about Pace of Life the countryside?",
    ],
  },
  // Unit 8
  {
    type: 1,
    unit: 8,
    data: [
      "beak into",
      "credible information",
      "misinformation",
      "check out",
      "on my own",
      "type in",
      "search engine",
      "access",
      "at my fingertips",
      "keep up with",
      "keep pace with",
      "keep in touch",
      "troubleshoot",
      "tend to",
    ],
  },
  {
    type: 2,
    unit: 8,
    data: [
      "A common worry with using the internet is the risk that someone might break into your personal accounts and steal your information.",
      "No, you cannot trust everything you see online. It's important to distinguish between credible information and misinformation by verifying facts from reliable sources.",
      "I explore new websites or online platforms by reading reviews and recommendations. I also check out different sections to understand their content.",
      "It can be okay for kids to use the internet early on if they are supervised and guided by parents. They should be encouraged to explore educational content and avoid harmful sites on their own.",
      "I buy things online by typing in the product I need in a search engine, visiting websites like Shopee and Lazada, and completing the purchase using secure payment methods.",
      "I usually access the internet through my smartphone or laptop, making sure it's always at my fingertips through Wi-Fi or mobile data.",
      "I keep up with the latest news by visiting reputable news websites, using news apps, and following news accounts on social media to keep pace with current events.",
      "I keep in touch with friends through messaging apps, social media platforms, and video calls.",
      "If I have trouble with the internet, I usually troubleshoot the issue by restarting my router, checking the connections, or contacting my internet service provider.",
      "I tend to find reliable information online by using credible sources, such as official websites, academic journals, and well-known news outlets.",
    ],
  },
  {
    type: 3,
    unit: 8,
    data: [
      "What's a common worry with using the internet?",
      "Can you trust everything you see online?",
      "How do you explore new websites or online platforms?",
      "Is it okay for kids to use the internet early on?",
      "How do you buy things online?",
      "How do you usually access the internet?",
      "How do you keep up with the latest news?",
      "How do you stay connected with friends?",
      "What do you do if you have trouble with the internet?",
      "How do you find reliable information online?",
    ],
  },
  // Unit 9
  {
    type: 1,
    unit: 9,
    data: [
      "the latest fashion trends",
      "keep up with",
      "be on trend",
      "high-street fashion",
      "timeless",
      "smart clothes",
      "have an eye for fashion",
      "mix and match",
      "take pride in my appearance",
      "dress for the occasion",
      "fashionable",
      "look good in",
      "goes out of style",
      "suits",
      "having your own sense of style",
      "get dressed up",
      "high-end fashion",
      "be back in fashion",
      "Hand-me-downs",
      "must-have items",
    ],
  },
  {
    type: 2,
    unit: 9,
    data: [
      "I feel most confident wearing light-colored clothes such as white, light blue, and light green.",
      "I don't usually keep up with the latest fashion trends; instead, I focus on timeless colors that suit me best.",
      "I decide what to wear based on the weather, my mood, and my activities.",
      "At home, I wear comfortable clothes. For work, I wear a uniform. When going out or traveling, I choose youthful and dynamic clothes that reflect my sense of style.",
      "I get my clothes from retail stores and online shops.",
      "Occasionally, I also wear hand-me-downs from family.",
      "For special events, I dress for the occasion with smart clothes.",
    ],
  },
  {
    type: 3,
    unit: 9,
    data: [
      "What colors do you feel most confident wearing?",
      "How do you decide what to wear each day?",
      "Where do your clothes usually come from?",
    ],
  },
  // Unit 10
  {
    type: 1,
    unit: 10,
    data: [
      "play soccer",
      "play football",
      "play basketball",
      "play tennis",
      "play volleyball",
      "play golf",
      "do yoga",
      "hit the gym",
      "do gymnastics",
      "do martial arts",
      "boost my mood",
      "keep fit",
      "stay healthy",
      "struggle with stress",
      "spend long hours sitting in front of a screen",
      "do aerobics",
      "go swimming",
      "go biking",
      "go bowling",
      "go fishing",
    ],
  },
  {
    type: 2,
    unit: 10,
    data: [
      "I like hitting the gym",
      "It helps me boost my mood",
      "It helps me keep fit",
      "It helps me stay healthy",
      "I struggle with stress",
      "I have a lot of tasks to do",
      "I also spend long hours sitting in front of a screen, which affects my eyes.",
      "Exercising helps me refresh my mind and relieve stress from work and study burdens.",
      "It also improves my sleep quality, so I feel more confident.",
      "I usually hit the gym every morning except for Sunday, which gives me more energy to work.",
      "It's a great way to start my day.",
      "I usually go to the fitness center, gym, or park to exercise alone, but sometimes I go with friends.",
    ],
  },
  {
    type: 3,
    unit: 10,
    data: [
      "Tell me about your favorite sport?",
      "What sport do you like?",
      "Why do you like hitting the gym?",
      "When do you usually hit the gym",
      "Who do you usually play with?",
      "Where do you usually play?",
    ],
  },
  // Unit 11
  {
    type: 1,
    unit: 11,
    data: [
      "unhealthy",
      "habit",
      "drink a lot of alcohol",
      "spend too much time working and studying",
      "maintain",
      "health",
      "hit the gym regularly",
      "boost my mood",
      "keep fit",
      "stay healthy",
      "improve immune system",
      "eat a balanced diet",
      "nutrient-rich foods",
      "minimize processed foods and sugary drinks",
      "vegetables",
      "fruits",
      "pay attention",
      "portions",
    ],
  },
  {
    type: 2,
    unit: 11,
    data: [
      "I have some unhealthy habits",
      "I spend too much time working and studying",
      "I drink a lot of alcohol.",
      "to maintain my health",
      "I hit the gym regularly",
      "it helps me boost my mood, keep fit, and stay healthy.",
      "I struggle with stress and have a lot of tasks to do.",
      "I also spend long hours sitting in front of a screen, which affects my eyes.",
      "Exercising helps me refresh my mind and relieve stress from work and study burdens.",
      "It also improves my sleep quality, so I feel more confident",
      "I eat a balanced diet.",
      "I usually choose nutrient-rich foods",
      "minimize processed foods and sugary drinks",
      "eat plenty of fruits and vegetables.",
      "I also pay attention to my portions when I eat to avoid overeating.",
    ],
  },
  {
    type: 3,
    unit: 11,
    data: ["What do you usually do to maintain your health?"],
  },
  // Unit 12
  {
    type: 1,
    unit: 12,
    data: [],
  },
  {
    type: 2,
    unit: 12,
    data: [],
  },
  {
    type: 3,
    unit: 12,
    data: [
      "Can you tell me about yourself?",
      "What are your hobbies?",
      "Do you prefer living in the city or the countryside?",
      "Do you like shopping?",
      "When do you usually go shopping?",
      "Where do you usually shop",
      "Did you play sports as a child?",
      "Do you think children should watch TV?",
      "What do you use the internet for?",
      "What's a common worry with using the internet?",
      "Can you trust everything you see online?",
      "How do you explore new websites or online platforms?",
      "Is it okay for kids to use the internet early on?",
      "How do you buy things online?",
      "How do you usually access the internet?",
      "How do you stay connected with friends?",
      "What do you do if you have trouble with the internet?",
      "How do you find reliable information online?",
      "What colors do you feel most confident wearing?",
      "How do you decide what to wear each day?",
      "Where do your clothes usually come from?",
      "Tell me about your favorite sport?",
      "What do you usually do to maintain your health?",
      "Do you like holidays? Why / why not?",
      "Do you prefer to travel or stay at home during holiday periods? Why?",
      "When do you prefer to take your holidays? Why?",
      "How much time do you spend at home?",
      "Do you prefer to spend your free time at home or outside the house?",
      "What do you do when you have some free time and you're at home?",
      "Do you live in a house or an apartment?",
      "Which is your favorite room in your home? Why?",
      "Where are you from?",
      "Do you like your home town? (Why?)",
      "Do you play any games?",
      "How do people learn to play games in your country?",
      "Do you like music?",
      "Do you prefer to study alone or with others? Why?",
      "Do you like reading?",
      "Do you prefer working alone or with others? Why?",
      "How often do you send e-mails?",
      "Do you like parks? Why / why not?",
      "How often do you visit parks?",
      "Do you usually see your friends during the week or at weekends?",
    ],
  },
];
