export const optionsType = [
  { label: "All", value: null },
  { label: "Word", value: 1 },
  { label: "Phrase", value: 2 },
  { label: "Question", value: 3 },
];

export const optionsTopic = [{ label: "Relationships", value: 1 }];

export const globalData = [
  {
    type: 1,
    unit: 1,
    data: [
      "parents",
      "father",
      "mother",
      "sibling",
      "brother",
      "sister",
      "older sister",
      "younger bother",
      "grandparent",
      "aunt",
      "uncle",
      "cousin",
      "affectionate",
      "supportive",
      "trustworthy",
      "dependable",
      "loyal",
      "respectful",
      "bond",
      "spend quality time",
      "distant",
      "loving",
      "reliable",
      "intimate",
      "get along with",
      "fall out with",
    ],
  },
  {
    type: 2,
    unit: 1,
    data: [
      "My parents always encourage me to do my best in university.",
      "Although my aunt lives far away, we stay connected through video calls and messaging apps.",
      "When I was younger, my cousins used to take us to the countryside on weekends, where we would explore nature and have picnics.",
      "It's important to communicate openly with your parents about your goals and dreams.",
      "My English teacher is very affectionate with her family, I appreciated her warmth and kindness.",
      "Although my uncle seems tough, but He is actually very affectionate with his teacher.",
      "I'm very trustworthy and never break promises.",
      "My close friend is very reliable and trustworthy, and everyone feels comfortable sharing their secrets with him.",
      "I highly recommend Jollie for the position, Being trustworthy is one of her best qualities, as people know they can rely on her in any situation.",
      "My favorite teacher in university was the one who encouraged my passion for technology and made learning enjoyable.",
      "I fell out with Jollie over a misunderstanding",
      "If you fall out with someone, try to communicate openly and honestly to resolve the issue and mend the relationship.",
      "She is always supportive she never hesitates to lend a helping hand.",
      "My dog is incredibly loyal and protective, he always watches over me.",
    ],
  },
  {
    type: 3,
    unit: 1,
    data: [
      "Do you have a close relationship with your family?",
      "How often do you see your friends?",
      "What is your major in university?",
    ],
  },
];
